version: '3.8'

services:
  app:
    build: .
    container_name: viticulture_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/viticulture_db
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: viticulture_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: viticulture_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
